<?php $layout = 'views/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/tablesorter/green/style.css'); ?>">
<?php block(); ?>

<h1>Joukkueet</h1>
<hr>

<table id="teams" class="tablesorter">
<thead>
<tr>
    <th colspan="2">Joukkue</th>
    <th>Lyhenne</th>
    <th>Sijoitus</th>
</tr>
</thead>
<tbody>
<?php foreach($teams as $team): ?>
<tr class="f32">
    <td  style="width: 32px; line-height: 32px; ">
        <div class="flag <?php echo $team['abbr']; ?>">&nbsp;</div>
    </td>
    <td width="40%" class="editable">
            <?php echo $team['name']; ?>
    </td>
    <td class="editable"><?php echo $team['abbr']; ?></td>
    <td class="editable"><?php echo $team['ranking']; ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery-tablesorter.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery-editinplace.js'); ?>"></script>
<script>
$(document).ready(function() {
    $('#teams').tablesorter();
    $('.editable').editInPlace({
        url: 'http://localhost',
        params: 'name=david'
    });
});
</script>
<?php block(); ?>