<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/tablesorter.css'); ?>">
<?php block(); ?>
<h1>Joukkueet</h1>
<hr>
<table id="teams" class="tablesorter">
<thead>
<tr>
    <th colspan="2">Joukkue</th>
    <th>Lyhenne</th>
    <th>Sijoitus</th>
</tr>
</thead>
<tbody>
<?php foreach($teams as $team): ?>
<tr class="f32">
    <td  style="width: 32px; line-height: 32px; ">
        <div class="flag <?php echo $team['abbr']; ?>">&nbsp;</div>
    </td>
    <td width="40%" class="editable">
            <?php echo $team['name']; ?>
    </td>
    <td><?php echo $team['abbr']; ?></td>
    <td>
        <form method="post" action="<?php echo url('~/bets/games/' . $team['name']); ?>" class="f16">
        <table>
        <tr>
            <td><input type="text" class="large" value="<?php echo $team['ranking']; ?>"></td>
            <td>&nbsp;</td>
            <td><input type="submit" value="Tallenna" disabled></td>
        </tr>
        </table>
        </form>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery.tablesorter.js'); ?>"></script>
<script>
$(document).ready(function() {
    $('#teams').tablesorter();
});
</script>
<?php block(); ?>