<?php $layout = 'layouts/layout.default.phtml'; ?>
<h1><?php echo $title; ?></h1>
<hr>
<?php if (isset($error)): ?>
<div class="error">
    Ottelun tiedot ovat virheelliset. Tarkista lomake.
</div>
<?php endif; ?>
<table id="bets">
<tr>
    <th>Päivämäärä</th>
    <th colspan="5">Ottelu</th>
    <th>Tulos / Toiminnot</th>
</tr>
<form method="post" action="<?php echo url('~/admin/games'); ?>">
<tr>
    <td align="right">
        <table>
        <tr style="border: none;">
            <td><input id="date" name="date" type="text" class="large" style="width: 70px; font-size: 1em;" /></td>
            <td align="right">
                <select name="time" class="large" style="width: 60px;">
                    <option value="14:30:00"<?php if ($form->time->value == '14:30:00') echo ' selected'; ?>>14:30</option>
                    <option value="17:00:00"<?php if ($form->time->value == '17:00:00') echo ' selected'; ?>>17:00</option>
                    <option value="21:30:00"<?php if ($form->time->value == '21:30:00') echo ' selected'; ?>>21:30</option>
                </select>
            </td>
        </tr>
        </table>
    </td>
    <td colspan="2" style="text-align: right;">
        <select name="home" class="large">
            <?php foreach ($teams as $team): ?>
                <option value="<?php echo $team['name']; ?>"<?php if ($form->home->value == $team['name']) echo ' selected'; ?>><?php echo $team['name'] ?></option>
            <?php endforeach; ?>
        </select>
    </td>
    <td class="dash">&ndash;</td>
    <td colspan="2">
        <select name="road" class="large">
            <?php foreach ($teams as $team): ?>
                <option value="<?php echo $team['name']; ?>"<?php echo $team['name']; ?>"<?php if ($form->road->value == $team['name']) echo ' selected'; ?>><?php echo $team['name'] ?></option>
            <?php endforeach; ?>
        </select>
    </td>
    <td align="right">
        <table>
        <tr style="border: none;">
            <td style="padding-top: 2px;"><input id="draw" type="checkbox" name="draw" disabled><label for="draw">Tasapeli</label></td>
            <td>&nbsp;&nbsp;&nbsp;</td>
            <td style="padding-top: 2px;"><input type="submit" value="Lisää" style="width: 87px; height: 31px;"></td>
        </tr>
        </table>
    </td>
</tr>
</form>
<?php $now = date_create(); foreach($games as $game): $date = date_create($game['time']); ?>
<tr>
    <td class="time" style="text-align: center;"><?php echo weekday($date, 2) . ' ' . date_format($date, 'j.n H:i'); ?></td>
    <td class="home"><?php echo $game['home']; ?></td>
    <td class="f32">
        <div class="flag <?php echo $game['home_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="dash">&ndash;</td>
    <td class="f32">
        <div class="flag <?php echo $game['road_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="road"><?php echo $game['road']; ?></td>
    <td class="bet" align="right">
        <form method="post" action="<?php echo url('~/admin/games/' . $game['id']); ?>">
        <table width="100%">
        <tr style="border: none;">
            <td><input type="text" class="large" name="home_goals" value="<?php echo $game['home_goals']; ?>"<?php if ($now < $date) echo ' disabled'; ?>></td>
            <td>&nbsp;</td>
            <td>&ndash;</td>
            <td>&nbsp;</td>
            <td><input type="text" class="large" name="road_goals" value="<?php echo $game['road_goals']; ?>"<?php if ($now < $date) echo ' disabled'; ?>></td>
            <td>&nbsp;</td>
            <td style="text-align: right;"><input type="submit" class="game" value="Tallenna"<?php if ($now < $date) echo ' disabled'; ?></td>
        </tr>
        </table>
        </form>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php block($scripts); ?>
<script>
function posted(data, status) {
    if (status != 'success') {
        alert('Ottelun tallennuksessa tapahtui virhe. Yritä uudelleen.');
    }
}
$('#draw').button();
$("#date").datepicker({ dateFormat: 'yy-mm-dd', showAnim: 'fadeIn' });
$('input:submit.game').each(function() {
    var input = $(this);
    var form = $(this.form);
    input.click(function() {
        $.post(form.attr('action'), form.serialize(), posted);
        return false;
    });
});
</script>
<?php block(); ?>