<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/tablesorter.css'); ?>">
<?php block(); ?>
<h1><?php echo $title; ?></h1>
<hr>
<table id="users" class="tablesorter">
    <thead>
    <tr>
        <th>Nimi</th>
        <th>Sähköposti</th>
        <th>Ylläpitäjä</th>
        <th>Aktiivinen</th>
        <th>Maksanut</th>
    </tr>
    </thead>
    <?php foreach($users as $u): ?>
    <tr>
        <td><?php echo $u['username']; ?></td>
        <td><?php echo $u['email']; ?></td>
        <td><?php echo $u['admin']; ?></td>
        <td><?php echo $u['active']; ?></td>
        <td><?php echo $u['paid']; ?></td>
    </tr>
    <?php endforeach; ?>
</table>

<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery.tablesorter.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery.editinplace.js'); ?>"></script>
<script>
$(document).ready(function() {
    $('#users').tablesorter();
    $('.editable').editInPlace({
        url: 'http://localhost',
        params: 'name=david'
    });
});
</script>
<?php block(); ?>