<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/countdown.css'); ?>">
<?php block(); ?>
<h1>Otteluveikkaus</h1>
<hr>
<table id="bets" style="padding: 2em !important;">
<tr>
    <th colspan="2">Päivämäärä / Kellonaika</th>
    <th colspan="5">Ottelu</th>
    <th>Veikkaus</th>
</tr>
<?php foreach($games as $game): ?>
<tr>
    <td class="weekday"><?php echo date_format(date_create($game['time']), 'l'); ?></td>
    <td class="time"><?php echo date_format(date_create($game['time']), 'd.h H:i'); ?></td>
    <td class="home"><?php echo $game['home']; ?></td>
    <td class="f32">
        <div class="flag <?php echo $game['home_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="dash">&ndash;</td>
    <td class="f32">
        <div class="flag <?php echo $game['road_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="road"><?php echo $game['road']; ?></td>
    <td class="bet">
        <form action="<?php echo url('~/bets/games/' . $game['id']); ?>" class="f16" style="display: none;">
            <input  id="home<?php echo $game['id']; ?>" type="radio" name="score" value="1" class="flag <?php echo $game['home_abbr']; ?>">
            <label for="home<?php echo $game['id']; ?>"><?php echo $game['home']; ?></label>
            <input  id="draw<?php echo $game['id']; ?>" type="radio" name="score" value="X">
            <label for="draw<?php echo $game['id']; ?>">Tasapeli</label>
            <input  id="road<?php echo $game['id']; ?>" type="radio" name="score" value="2" class="flag <?php echo $game['road_abbr']; ?>">
            <label for="road<?php echo $game['id']; ?>"><?php echo $game['road']; ?></label>
        </form>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php block($scripts); ?>

<script>
function posted(data, status) {
    alert('jee');
}

$('input:radio').each(function() {
    var input = $(this);
    if (input.hasClass('flag')) {
        input.button({
            icons: {
                primary: input.attr('class')
            },
            text: false
        });
    } else {
        input.button({
            icons: {
                primary: 'ui-icon-close'
            },
            text: false
        });
    }
    var form = $(this.form);
    input.click(function() {
        $.post(form.attr('action'), form.serialize(), posted);
    });
});

$('form').buttonset().toggle();
/*
$('label').qtip({
    show: 'mouseover',
    hide: 'mouseout',
    position: {
        corner: {
            target: 'topCenter',
            tooltip: 'bottomCenter'
        }
    }
});
*/
/*
$('input:radio').each(function() {
    if ($(this).hasClass('flag')) {
        $(this).button({ icons: { primary: $(this).attr('class') }});
    }
});

$('input:radio').each(function() {
    if ($(this).hasClass('flag')) {
        $(this).button({ icons: { primary: $(this).attr('class') }});
    }
    var form = $(this.form);
    $(this).click(function() {
        alert(form.attr('action'));
        $.post(form.attr('action'), form.serialize(), function(data, status) {
            alert(status);
            alert(data.game + ' ' + data.score);
        }, 'json');

    });
});
var newYear = new Date();
newYear = new Date(newYear.getTime() + 50000);
$('#defaultCountdown').countdown({until: newYear, format: 'hms', tickInterval: 5, onExpiry: function() {
    $(this).parent('div').css('line-height', '29px');
    $(this).parent('div').html('Ottelu on alkanut');
    $('input:radio').each(function() {
        $(this).button('disable');
    });
}});
*/
</script>
<?php block(); ?>