<?php $layout = 'views/layout.default.phtml'; ?>

<?php block($css); ?>
<?php block(); ?>

<h1>Chatti</h1>
<hr>

<div id="chat" style="height:315px; overflow: hidden;">
    <?php echo $messages; ?>
</div>
<br>

<div class="ui-widget">
    <form id="chat-form">
        <div class="grid_7 alpha"><input id="chatmessage" name="chatmessage" type="text" style="display: block; width: 100%;" /></div>
        <div class="grid_2 omega"><input type="submit" value="Lähetä viesti" /></div>
    </form>
</div>

<table>
 <tr>
  <td>:) =</td><td style='width: 19px; height: 19px;'><img src="<?php echo url('~/img/smileys/smile.gif'); ?>" alt=":)" /></td>
  <td style="padding-left: 7px;">:D =</td><td style='width: 19px; height: 19px;'><img src="<?php echo url('~/img/smileys/lol.gif'); ?>" alt=":D" /></td>
  <td style="padding-left: 7px;">(y) =</td><td style='width: 19px; height: 19px;'><img src="<?php echo url('~/img/smileys/thumb.gif'); ?>" alt="(y)" /></td>
  <td style="padding-left: 7px;">(b) =</td><td style='width: 19px; height: 19px;'><img src="<?php echo url('~/img/smileys/beer.gif'); ?>" alt="(b)" /></td>
 </tr>
</table>

<?php block($scripts); ?>
<script>
$(document).ready(function() {

    $.ajaxSetup({cache: false})

    setInterval(function() {
        $.get('<?php echo url('~/chat/poll'); ?>', function(data) { $('#chat').html(data); });
    }, 1000);

    $('#chat-form').submit(function() {
        $.post('<?php echo url('~/chat'); ?>', $(this).serialize());
        $('#chatmessage').val('').focus();
        return false;
    });
});
</script>
<?php block(); ?>