<?php foreach($messages as $message): ?>
<div>
    <div class="time" style="float: left;">[<span><?php echo date_format(date_create($message['time']), 'H:i'); ?></span>]</div>
    <div class="user" style="float: left; padding: 0 0.5em;">&lt;<?php echo $message['user']; ?>&gt;</div>
    <div class="message" style="overflow:hidden;"><?php echo $message['message']; ?></div>
</div>
<div class="clear"></div>
<?php endforeach; ?>