<!DOCTYPE html>
<html lang="fi">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
<?php if (isset($meta)) echo $meta; ?>
<title></title>
<link rel="stylesheet" href="<?php echo url('~/css/typography.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/ui/dark-hive/jquery-ui.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/flags.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/960.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/menu.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/main.css'); ?>">
<?php if (isset($css)) echo $css; ?>
</head>
<body id="default">
<div id="container" class="container_12">
<div id="container-top">
    <div id="header" class="ui-corner-top">
        <img id="logo" src="<?php echo url('~/img/logo.png'); ?>">
        <img id="logo-text" src="<?php echo url('~/img/logo-text.png'); ?>">
    </div>
    <div id="navigation">
        <div id="menu">
            <ul class="menu">
                <li><a href="<?php echo url('~/news'); ?>" class="parent"><span>Etusivu</span></a></li>
                <li><a href="<?php echo url('~/bets/games'); ?>"><span>Otteluveikkaus</span></a></li>
                <li><a href="<?php echo url('~/bets/teams'); ?>"><span>Kolmen kärki</span></a></li>
                <li><a href="<?php echo url('~/bets/scorer'); ?>"><span>Maalikuninkuus</span></a></li>
                <li><a href="<?php echo url('~/stats'); ?>"><span>Tilastot</span></a></li>
                <li><a href="<?php echo url('~/chat'); ?>"><span>Chatti</span></a></li>
                <li class="last" >
                    <a href="#"><span>Ylläpito</span></a>
                    <ul>
                        <li><a href="<?php echo url('~/admin/games'); ?>"><span>Ottelut</span></a></li>
                        <li><a href="<?php echo url('~/admin/teams'); ?>"><span>Joukkueet</span></a></li>
                        <li><a href="<?php echo url('~/admin/scorers'); ?>"><span>Maalintekijät</span></a></li>
                        <li><a href="<?php echo url('~/admin/users'); ?>"><span>Käyttäjät</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<div id="container-main">
    <div id="main">
        <div id="main-left" class="grid_9">
            <?php echo $view; ?>
        </div>
        <div id="main-right" class="grid_3">
            <div class="block">
                <h3 class="ui-corner-top">Paikalla</h3>
                <div class="ui-corner-bottom">
                    bungle<br />
                    matias
                </div>
            </div>
            <div class="block-spacer"></div>
            <div class="block">
                <h3 class="ui-corner-top">Seuraava ottelu</h3>
                <div class="ui-corner-bottom">
                    Ruotsi - Suomi
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clear bottom-spacer"></div>

<div id="container-bottom">
    <div id="footer">
        <div class="grid_12">
            <span>
                Tekninen toteutus: <a href="http://www.php.net/">PHP</a>, <a href="http://code.google.com/p/web-dot-php/">web.php</a>, <a href="http://www.sqlite.org/">SQLite</a>, <a href="http://jquery.com/">jQuery</a> <a href="http://jqueryui.com/">UI</a>, <a href="http://apycom.com/">Apycom Menus</a>, <a href="http://960.gs/">960 Grid System</a>
            </span>
            <span style="float: right;">
                Sivun suoritusaika: <span class="time"><?php global $starttime; echo number_format((microtime(true) - $starttime) * 1000, 2, ',', ' '); ?></span> millisekuntia.
            </span>
        </div>
    </div>
</div>
</div>
<script src="<?php echo url('~/js/jquery.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery-ui.js'); ?>"></script>
<script src="<?php echo url('~/js/menu.js'); ?>"></script>
<script src="<?php echo url('~/js/main.js'); ?>"></script>
<?php if (isset($scripts)) echo $scripts; ?>
</body>
</html>
