<!DOCTYPE html>
<html lang="fi">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<?php if (isset($meta)) echo $meta; ?>
<title></title>
<link rel="stylesheet" href="<?php echo url('~/css/typography.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/ui/dark-hive/jquery-ui.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/login.css'); ?>">
<?php if (isset($css)) echo $css; ?>
</head>
<body id="default">
<div id="wrapper">
    <div id="content">
        <div id="login">
            <?php echo $view; ?>
        </div>
    </div>
</div>
<script src="<?php echo url('~/js/jquery.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery-ui.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery-qtip.js'); ?>"></script>
<script src="<?php echo url('~/js/main.js'); ?>"></script>
<?php if (isset($scripts)) echo $scripts; ?>
</body>
</html>
