<!DOCTYPE html>
<html lang="fi">
<head>
<meta charset="utf-8">
<?php if (isset($meta)) echo $meta; ?>
<title></title>
<link rel="stylesheet" href="<?php echo url('~/css/reset.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/typography.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/grid.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/ui/south-street/jquery-ui.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/flags16.css'); ?>">
<?php if (isset($css)) echo $css; ?>
</head>
<body id="default">
<br>
<div class="row">
    <div class="column grid_8">
        <?php echo $view; ?>
    </div>
    <div class="column grid_4">
        <h5>Oikea palsta</h5>
        <p>Lorem...</p>
    </div>
</div>
<div class="row">
    <div class="column grid_12">
        Sivun suoritusaika <?php global $starttime; echo (microtime(true) - $starttime) * 1000; ?> millisekuntia.
    </div>
</div>
<script src="<?php echo url('~/js/jquery.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery-ui.js'); ?>"></script>
<?php if (isset($scripts)) echo $scripts; ?>
</body>
</html>