<?php $layout = 'layouts/layout.default.phtml'; ?>
<h1><?php echo $title; ?></h1>
<hr>
<div id="seadragon"></div>
<?php block($right); ?>
<div class="block-spacer"></div>
<div class="block">
    <h3 class="ui-corner-top">Ladattava materiaali</h3>
    <div class="ui-corner-bottom">
        <h4 class="file excel"><a href="<?php echo url('~/files/score-sheet-2.xls'); ?>">Tulostaulukko</a></h4>
        <h4 class="file pdf"><a href="<?php echo url('~/files/analysis.pdf'); ?>">J.P.Morgan -analyysi</a></h4>
    </div>
</div>
<?php block(); ?>
<?php block($scripts); ?>
<script type="text/javascript" src="http://seadragon.com/ajax/0.8/seadragon-min.js"></script>
<script>
Seadragon.Config.imagePath = '<?php echo url('~/img') . '/' ; ?>';
var viewer = new Seadragon.Viewer("seadragon");
viewer.openDzi('<?php echo url('~/img/charts2/dzc_output.xml'); ?>');
</script>
<?php block(); ?>