<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<?php block(); ?>
<h1>S&auml;&auml;nn&ouml;t</h1>
<hr />
<div class="block">
    <h3 class="ui-corner-top rules">Otteluveikkaus</h3>
    <div class="ui-corner-bottom">
        Alkulohkon otteluissa voi veikata voittajaa tai tasapeliä. Pudotuspeleissä vain voittajalla on merkitystä. Jokaisesta oikein veikatusta ottelusta veikkaaja saa kaksi pistettä vähennettynä
        oman veikkauksensa prosentuaalinen osuus koko veikkausjakaumasta.<br /><br />
        Esimerkki:<br />
        60% veikkasi Ranskaa voittajaksi ja 20% tasapeliä, loput 20% veikkasi Ruotsia. Ruotsi voitti pelin, joten Ruotsia veikanneet saavat 2-0.2 eli 1.8 pistettä.
        Osuudet lasketaan kahden desimaalin tarkkuudella. Prosentit lasketaan ainoastaan veikatuista äänistä, joten veikkaamatta jättäneet eivät vaikuta "kertoimiin". Tällä kertaa
        siis altavastaajia veikkaavia palkitaan ruhtinaallisemmin.<br /><br />
        Väärin veikatuista ei rangaista.<br /><br />
        Kilpailussa on mukana 32 joukkuetta, jotka on jaettu kahdeksaan lohkoon. Jokaisessa lohkossa pelataan kuusi ottelua. Alkulohkon pelejä on siis yhteensä 48. Jatkoon pääsee 16 joukkuetta
        ja jatkopelejä on yhteensä 14.<br /><br />
        Pelikohtainen veikkaus sulkeutuu minuuttia ennen ottelun ilmoitettua alkamisajankohtaa. Tämän jälkeen veikkaaminen ei enää onnistu.
        Veikkaamatta jätetyt ottelut jätetään huomioimatta, eli pelaaja ei saa niistä minkäänlaisia pisteitä.
    </div>
</div>
<br />
<div class="block">
    <h3 class="ui-corner-top rules">Kolmen kärki&trade;</h3>
    <div class="ui-corner-bottom">
        Kolmen kärjessä pelaaja veikkaa turnauksen kolmea parasta maata. Pisteet jaetaan sen mukaan onko kyseinen maa kolmen parhaan joukossa turnauksen loputtua.
        Lisäpisteitä saa oikeasta sijoituksesta. Samaa maata ei voi veikata kuin kerran. Jos veikattu maa on kolmen joukossa, saa pelaaja pisteen. Jos se on myös 
        oikealla sijalla, saa pelaaja pisteitä seuraavasti: voittajamaa oikein antaa kolme pistettä,hopeamaa oikein antaa kaksi pistettä ja pronssimaasta saa pisteen. 
        Kolmen kärkeä voi veikata ennen turnauksen ensimmäistä peliä.<br /><br />
        Jaossa on siis enintään yhdeksän pistettä.<br /><br />
        Esimerkki:<br /><br />
        Pelaaja A veikkaa Kolmen kärkeen Italiaa, Espanjaa sekä Ranskaa tässä järjestyksessä. Näistä maista Italia sekä Ranska ovat kolmen joukossa. Pelaaja A saa
        pisteen per oikea joukkue eli yhteensä kaksi pistettä. Italia voitti mestaruuden ja Ranska oli hopealla eli pelaaja A saa kolme lisäpistettä Italian oikeasta
        sijoituksesta. Yhteensä pelaaja A saa siis viisi pistettä. 
    </div>
</div>
<br />
<div class="block">
    <h3 class="ui-corner-top rules">Maalikuninkuus</h3>
    <div class="ui-corner-bottom">
        Maalikuninkuudessa veikataan turnauksen parasta maalintekijää. Oikeasta veikkauksesta saa kolme pistettä. Veikata voi ennen turnauksen ensimmäistä peliä. 
    </div>
</div>
<br />
<div class="block">
    <h3 class="ui-corner-top rules">Maksaminen</h3>
    <div class="ui-corner-bottom">
        TBD
    </div>
</div>
<br />
<div class="block">
    <h3 class="ui-corner-top rules">Yhteenveto</h3>
    <div class="ui-corner-bottom">
        Jaossa on siis yhdeksän pistettä Kolmen kärjestä, kolme pistettä Maalikuninkuudesta ja otteluveikkauksista omansa.<br /><br />
        Kymmenen euron osallistumismaksusta menee 80% voittajalle ja 20% toiseksi tulleelle. Jos useita pelaajia on tasatilanteessa pistelaskun jälkeen,
        jaetaan summa heidän kesken. Pistetilannetta voi seurata tilastoista. Peli-iloa! :)
    </div>
</div>