<?php $layout = 'layouts/layout.login.phtml'; ?>
<h1 class="ui-corner-top">Virhe World Cup 2010 -hupilyönnissä</h1>
<div>
    <div class="error">
        Valitettavasti sivua käsiteltäessä tapahtui virhe.
        Virhe on kirjattu virhelokiin ja ylläpito pyrkii ratkaisemaan ongelmat mahdollisimman pian.
        Virhe voi olla myös väliaikainen, joten voit yrittää ladata haluamaasi sivua uudestaan.
    </div>
    <div class="success" style="margin-bottom: 0;">
        Mikäli haluat raportoida ongelmasta, voit lähettää sähköpostia ylläpidolle:<br>
        <a href="mailto:worldcup2010@fchaps.com">worldcup2010@fchaps.com</a>.
    </div>
</div>
<h3 class="ui-corner-bottom">Virhe World Cup 2010 -hupilyönnissä.</h3>