<?php $layout = 'layouts/layout.default.phtml'; ?>
<h1><?php echo $title; ?></h1>
<hr>
<table id="bets">
<tr>
    <th>Päivämäärä</th>
    <th colspan="5">Ottelu</th>
    <th>Tulos</th>
</tr>
<?php foreach($games as $game): $date = date_create($game['time']); ?>
<tr>
    <td class="time"><?php echo weekday($date, 2) . ' ' . date_format($date, 'j.n H:i'); ?></td>
    <td class="home"><?php echo $game['home']; ?></td>
    <td class="f32">
        <div class="flag <?php echo $game['home_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="dash">&ndash;</td>
    <td class="f32">
        <div class="flag <?php echo $game['road_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="road"><?php echo $game['road']; ?></td>
    <td class="bet">
        <form method="post" action="<?php echo url('~/bets/games/' . $game['id']); ?>" class="f16">
        <table>
        <tr>
            <td><input type="text" class="large" size="1"></td>
            <td>&nbsp;</td>
            <td class="dash">&ndash;</td>
            <td>&nbsp;</td>
            <td><input type="text" class="large" size="1"></td>
            <td>&nbsp;</td>
            <td><input type="submit" value="Tallenna" disabled></td>
        </tr>
        </table>
        </form>
    </td>
</tr>
<?php endforeach; ?>
</table>