<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<?php block(); ?>
<h1>Lisää uutinen</h1>
<hr />
<?php
if(isset($success)) {
    echo "<span style='font-size: 1.2em; font-weight: bold; color: #76B737'>$success</span>";
}
?>
<form action="<?php echo url('~/admin/news'); ?>" method="post">
    <h3>Otsikko</h3>
    <input name="title" type="text" style="width: 70%" />
    <h3>Sisältö</h3>
    <textarea id="newseditor" name="content" rows="20" cols="59"></textarea><br />
    <input type="checkbox" value="1" name="level" /> Tärkeä
    <br /><br />
    <input type="submit" value="Tallenna" />
</form>



<script src="<?php echo url('~/js/nicEdit.js'); ?>"></script>

<script type="text/javascript">
//<![CDATA[
bkLib.onDomLoaded(function() { 
    new nicEditor({iconsPath : '<?php echo url("~/img/nicEditorIcons.gif'");?>}, {fullPanel : true}).panelInstance('newseditor');
});
//]]>
</script>