<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/countdown.css'); ?>">
<?php block(); ?>
<h1><?php echo $title; ?></h1>
<hr>
<table id="bets" style="display: none;">
<tr>
    <th>Päivämäärä</th>
    <th colspan="5">Ottelu</th>
    <th>H-hetki</th>
    <th>Veikkaus</th>
</tr>
<?php
foreach($games as $game): $date = date_create($game['time']); ?>
<tr>
    <td class="time"><?php echo weekday($date, 2) . ' ' . date_format($date, 'j.n H:i'); ?></td>
    <td class="home"><?php echo $game['home']; ?></td>
    <td class="f32">
        <div class="flag <?php echo $game['home_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="dash">&ndash;</td>
    <td class="f32">
        <div class="flag <?php echo $game['road_abbr']; ?>">&nbsp;</div>
    </td>
    <td class="road"><?php echo $game['road']; ?></td>
    <td class="countdown"><span style="font-weight: bold;" class="counter"><?php echo date_format($date, 'U'); ?>000</span></td>
    <td class="bet">
        <form method="post" action="<?php echo url('~/bets/games/' . $game['id']); ?>" class="f16">
            <input  id="home-<?php echo $game['id']; ?>" type="radio" name="score" value="1" <?php if ($game['score'] == '1') echo 'checked'; ?> class="flag <?php echo $game['home_abbr']; ?>">
            <label for="home-<?php echo $game['id']; ?>"><?php echo $game['home']; ?></label>
            <input  id="draw-<?php echo $game['id']; ?>" type="radio" name="score" value="X" <?php if ($game['score'] == 'X') echo 'checked'; ?>>
            <label for="draw-<?php echo $game['id']; ?>">Tasapeli</label>
            <input  id="road-<?php echo $game['id']; ?>" type="radio" name="score" value="2" <?php if ($game['score'] == '2') echo 'checked'; ?> class="flag <?php echo $game['road_abbr']; ?>">
            <label for="road-<?php echo $game['id']; ?>"><?php echo $game['road']; ?></label>
        </form>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php block($scripts); ?>
<script src="<?php echo url('~/js/jquery.blockui.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery.countdown.js'); ?>"></script>
<script>
$.blockUI({
    message: '<h2>Ladataan otteluita...</h2>(jQuery UI:n bugi hidastaa lataamista)',
    css: {
        border: 'none',
        padding: '15px',
        backgroundColor: '#000',
        '-webkit-border-radius': '10px',
        '-moz-border-radius': '10px',
        opacity: .5,
        color: '#fff'
    },
    fadeIn: 0,
    fadeOut: 200
});

setTimeout(initialize, 50);

function posted(data, status) {
    if (status != 'success') {
        alert('Otteluveikkauksen tallennuksessa tapahtui virhe. Yritä uudelleen.');
    }
}

function initialize() {
    $('input:radio').each(function() {
        var input = $(this);
        if (input.hasClass('flag')) {
            input.button({
                icons: {
                    primary: input.attr('class')
                },
                text: false
            });
        } else {
            input.button({
                icons: {
                    primary: 'ui-icon-close'
                },
                text: false
            });
        }
        var form = $(this.form);
        input.click(function() {
            $.post(form.attr('action'), form.serialize(), posted);
        });
    });

    $('form').buttonset();
    $('.counter').each(function() {
        var time = new Date(parseInt($(this).html()));
        $(this).countdown({
            until: time,
            format: 'dhm',
            tickInterval: 10,
            onExpiry: function() {
            }
        });
    });
    $('#bets').toggle();

    $.unblockUI();
}

var newYear = new Date();
newYear = new Date(newYear.getTime() + 50000);
$('#defaultCountdown').countdown({until: newYear, format: 'hms', tickInterval: 5, onExpiry: function() {
    $(this).parent('div').css('line-height', '29px');
    $(this).parent('div').html('Ottelu on alkanut');
    $('input:radio').each(function() {
        $(this).button('disable');
    });
}});
</script>
<?php block(); ?>