<?php $layout = 'views/layout.default.phtml'; ?>

<?php block($css); ?>
<?php block(); ?>

<h1>Chatti</h1>
<hr>

<div id="chat" style="height:315px; overflow: hidden;">
    <?php echo $messages; ?>
</div>
<br>

<div class="ui-widget">
    <form id="chat-form">
        <div class="grid_7 alpha"><input id="chat-message" name="chat-message" type="text" style="display: block; width: 100%;" /></div>
        <div class="grid_2 omega"><input type="submit" value="Lähetä viesti" /></div>
    </form>
</div>
    

<?php block($scripts); ?>
<script>
$(document).ready(function() {

    $.ajaxSetup({cache: false})

    setTimeout(function() {
        $.get('<?php echo url('~/chat/poll'); ?>', function(data) { $('#chat').html(data); });
        setTimeout(arguments.callee, 1000);
    }, 1000);

    $('#chat-form').submit(function() {
        $.post('<?php echo url('~/chat'); ?>', $(this).serialize());
        $('#chat-message').val('').focus();
        return false;
    });
});
</script>
<?php block(); ?>