<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<?php block(); ?>
<h1><?php echo $title; ?></h1>
<hr>
<div class="error">
    Valitettavasti sivua käsiteltäessä tapahtui virhe.
    Virhe on kirjattu virhelokiin ja ylläpito pyrkii ratkaisemaan ongelmat mahdollisimman pian.
    Virhe voi olla myös väliaikainen, joten voit yrittää ladata haluamaasi sivua uudestaan.
</div>
<div class="success" style="margin-bottom: 0;">
    Mikäli haluat raportoida ongelmasta, voit lähettää sähköpostia ylläpidolle:
    <a href="mailto:worldcup2010@fchaps.com">worldcup2010@fchaps.com</a>.
</div>
<?php block($scripts); ?>
<?php block(); ?>