<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/tablesorter.css'); ?>">
<?php block(); ?>
<h1>Euro2008 lopputulokset</h1>
<hr />
<table id="points" class="tablesorter">
 <thead>
   <tr>
        <th><img src="/examples/phpbetz/img/ranking.png" width="16" height="16" title="Sijoitus" alt="Sijoitus"></th>

        <th>Nimi</th>
        <th><img src="/examples/phpbetz/img/medal-gold.png" width="16" height="16" title="Voittaja" alt="Voittaja"></th>
        <th><img src="/examples/phpbetz/img/medal-silver.png" width="16" height="16" title="Hopeamitalisti" alt="Hopeamitalisti"></th>
        <th><img src="/examples/phpbetz/img/medal-bronze.png" width="16" height="16" title="Pronssimitalisti" alt="Pronssimitalisti"></th>
        <th>Maalikuningas</th>
        <th><img src="/examples/phpbetz/img/soccer.png" width="16" height="16" title="Ottelupisteet" alt="Ottelupisteet"></th>
        <th><img src="/examples/phpbetz/img/teams.png" width="48" height="16" title="Kolmen kärki &trade; pisteet" alt="Kolmen kärki &trade; pisteet"></th>
        <th><img src="/examples/phpbetz/img/scorer.png" width="16" height="16" title="Maalikuninkuuspisteet" alt="Maalikuninkuuspisteet"></th>

        <th><img src="/examples/phpbetz/img/sum.png" width="16" height="16" title="Pisteet yhteensä" alt="Pisteet yhteensä"></th>
    </tr>
</thead>
<tbody>
<tr>
        <td class="position" rowspan="1"><h3>1.</h3></td>
        <td>Rubberduck</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>

    <td>20</td>
    <td>7</td>
    <td>0</td>
    <td>27</td>
</tr>
<tr>
        <td class="position" rowspan="1"><h3>2.</h3></td>

        <td>Massimo</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Lukas Podolski</td>
    <td>19</td>
    <td>7</td>
    <td>0</td>
    <td>26</td>

</tr>
<tr>
        <td class="position" rowspan="1"><h3>3.</h3></td>
        <td>Kauko</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Lukas Podolski</td>
    <td>18</td>
    <td>7</td>

    <td>0</td>
    <td>25</td>
</tr>
<tr>
        <td class="position" rowspan="1"><h3>4.</h3></td>
        <td>Jeppe</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>

    <td>17</td>
    <td>7</td>
    <td>0</td>
    <td>24</td>
</tr>
<tr>
        <td class="position" rowspan="4"><h3>5.</h3></td>

        <td>hc</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Lukas Podolski</td>
    <td>16</td>
    <td>7</td>
    <td>0</td>
    <td>23</td>

</tr>
<tr>

        <td>JP2414</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag tr" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td>Fernando Torres</td>
    <td>17</td>
    <td>6</td>

    <td>0</td>
    <td>23</td>
</tr>
<tr>

        <td>schleiz</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>David Villa</td>

    <td>18</td>
    <td>2</td>
    <td>3</td>
    <td>23</td>
</tr>
<tr>


        <td>Sexyleiz</td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag ru" title="">&nbsp;</div>
    </td>
    <td>Karim Benzema</td>
    <td>18</td>
    <td>5</td>
    <td>0</td>
    <td>23</td>

</tr>
<tr>
        <td class="position" rowspan="2"><h3>6.</h3></td>
        <td>Ilona</td>
    <td class="f32">
        <div class="flag ru" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Luca Toni</td>
    <td>17</td>
    <td>4</td>

    <td>0</td>
    <td>21</td>
</tr>
<tr>
      
        <td>ode</td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Bafetimbi Gomis</td>

    <td>18</td>
    <td>3</td>
    <td>0</td>
    <td>21</td>
</tr>
<tr>
        <td class="position" rowspan="4"><h3>7.</h3></td>

        <td>Gorba</td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>18</td>
    <td>2</td>
    <td>0</td>
    <td>20</td>

</tr>
<tr>
        
        <td>Jarmo</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ru" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>17</td>
    <td>3</td>

    <td>0</td>
    <td>20</td>
</tr>
<tr>
        
        <td>matias</td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Robin van Persie</td>

    <td>16</td>
    <td>4</td>
    <td>0</td>
    <td>20</td>
</tr>
<tr>
        

        <td>wouinen</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>18</td>
    <td>2</td>
    <td>0</td>
    <td>20</td>

</tr>
<tr>
        <td class="position" rowspan="11"><h3>8.</h3></td>
        <td>apietari</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Pavel Pogrebnyak</td>
    <td>15</td>
    <td>4</td>

    <td>0</td>
    <td>19</td>
</tr>
<tr>
        
        <td>artturii</td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>

    <td>16</td>
    <td>3</td>
    <td>0</td>
    <td>19</td>
</tr>
<tr>
        

        <td>ergy</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>18</td>
    <td>1</td>
    <td>0</td>
    <td>19</td>

</tr>
<tr>
        
        <td>etm101</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>17</td>
    <td>2</td>

    <td>0</td>
    <td>19</td>
</tr>
<tr>
        
        <td>julle</td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Karim Benzema</td>

    <td>16</td>
    <td>3</td>
    <td>0</td>
    <td>19</td>
</tr>
<tr>
        

        <td>Juppe</td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td>Fernando Torres</td>
    <td>14</td>
    <td>5</td>
    <td>0</td>
    <td>19</td>

</tr>
<tr>
        
        <td>Tazio</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>18</td>
    <td>1</td>

    <td>0</td>
    <td>19</td>
</tr>
<tr>
        
        <td>Tinde</td>
    <td class="f32">
        <div class="flag ru" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag hr" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Fernando Torres</td>

    <td>18</td>
    <td>1</td>
    <td>0</td>
    <td>19</td>
</tr>
<tr>
        

        <td>Tumautus</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag NED" title="">&nbsp;</div>
    </td>
    <td>Ruud van Nistelrooy</td>
    <td>18</td>
    <td>1</td>
    <td>0</td>
    <td>19</td>

</tr>
<tr>
        
        <td>tummaparoni</td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>19</td>
    <td>0</td>

    <td>0</td>
    <td>19</td>
</tr>
<tr>
        
        <td>Voittaja34</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>

    <td>17</td>
    <td>2</td>
    <td>0</td>
    <td>19</td>
</tr>
<tr>
        <td class="position" rowspan="4"><h3>9.</h3></td>

        <td>koskinen</td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>17</td>
    <td>1</td>
    <td>0</td>
    <td>18</td>

</tr>
<tr>
        
        <td>pj.haaja</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td>Karim Benzema</td>
    <td>17</td>
    <td>1</td>

    <td>0</td>
    <td>18</td>
</tr>
<tr>
        
        <td>Riku</td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>

    <td>15</td>
    <td>3</td>
    <td>0</td>
    <td>18</td>
</tr>
<tr>
        

        <td>teemuhopeasaari</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>17</td>
    <td>1</td>
    <td>0</td>
    <td>18</td>

</tr>
<tr>
        <td class="position" rowspan="7"><h3>10.</h3></td>
        <td>2201</td>
    <td class="f32">
        <div class="flag GRE" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag se" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ru" title="">&nbsp;</div>
    </td>
    <td>Milan Baros</td>
    <td>15</td>
    <td>2</td>

    <td>0</td>
    <td>17</td>
</tr>
<tr>
        
        <td>alucey</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag se" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>

    <td>16</td>
    <td>1</td>
    <td>0</td>
    <td>17</td>
</tr>
<tr>
        

        <td>Jekkeri</td>
    <td class="f32">
        <div class="flag cz" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Fernando Torres</td>
    <td>13</td>
    <td>4</td>
    <td>0</td>
    <td>17</td>

</tr>
<tr>
        
        <td>nestehukka</td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Luca Toni</td>
    <td>16</td>
    <td>1</td>

    <td>0</td>
    <td>17</td>
</tr>
<tr>
        
        <td>oggi</td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td>David Villa</td>

    <td>13</td>
    <td>1</td>
    <td>3</td>
    <td>17</td>
</tr>
<tr>
        

        <td>pikku-timo</td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>16</td>
    <td>1</td>
    <td>0</td>
    <td>17</td>

</tr>
<tr>
        
        <td>tsido</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>15</td>
    <td>2</td>

    <td>0</td>
    <td>17</td>
</tr>
<tr>
        <td class="position" rowspan="4"><h3>11.</h3></td>
        <td>5553212</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Nuno Gomes</td>

    <td>15</td>
    <td>1</td>
    <td>0</td>
    <td>16</td>
</tr>
<tr>
        

        <td>bungle</td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Jan Koller</td>
    <td>15</td>
    <td>1</td>
    <td>0</td>
    <td>16</td>

</tr>
<tr>
        
        <td>Tatu</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag se" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>15</td>
    <td>1</td>

    <td>0</td>
    <td>16</td>
</tr>
<tr>
        
        <td>trollkiller</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>

    <td>14</td>
    <td>2</td>
    <td>0</td>
    <td>16</td>
</tr>
<tr>
        <td class="position" rowspan="7"><h3>12.</h3></td>

        <td>dfl</td>
    <td class="f32">
        <div class="flag ru" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag hr" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td>Pavel Pogrebnyak</td>
    <td>14</td>
    <td>1</td>
    <td>0</td>
    <td>15</td>

</tr>
<tr>
        
        <td>mipeni</td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>12</td>
    <td>3</td>

    <td>0</td>
    <td>15</td>
</tr>
<tr>
        
        <td>sirene</td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag cz" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>

    <td>15</td>
    <td>0</td>
    <td>0</td>
    <td>15</td>
</tr>
<tr>
        

        <td>Terastine</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td>Miroslav Klose</td>
    <td>14</td>
    <td>1</td>
    <td>0</td>
    <td>15</td>

</tr>
<tr>
        
        <td>texi</td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>12</td>
    <td>3</td>

    <td>0</td>
    <td>15</td>
</tr>
<tr>
        
        <td>Vape</td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td>Nuno Gomes</td>

    <td>14</td>
    <td>1</td>
    <td>0</td>
    <td>15</td>
</tr>
<tr>
       

        <td>vesseli</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>13</td>
    <td>2</td>
    <td>0</td>
    <td>15</td>

</tr>
<tr>
        <td class="position" rowspan="2"><h3>13.</h3></td>
        <td>ekii</td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag hr" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>14</td>
    <td>0</td>

    <td>0</td>
    <td>14</td>
</tr>
<tr>
        
        <td>HookanLoop</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Karim Benzema</td>

    <td>12</td>
    <td>2</td>
    <td>0</td>
    <td>14</td>
</tr>
<tr>
        <td class="position" rowspan="3"><h3>14.</h3></td>

        <td>kaitsu57</td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="flag NED" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>12</td>
    <td>1</td>
    <td>0</td>
    <td>13</td>

</tr>
<tr>
        
        <td>Mari</td>
    <td class="f32">
        <div class="flag ITA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag NED" title="">&nbsp;</div>
    </td>
    <td>Cristiano Ronaldo</td>
    <td>13</td>
    <td>0</td>

    <td>0</td>
    <td>13</td>
</tr>
<tr>
        
        <td>mpel</td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag FRA" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag ESP" title="">&nbsp;</div>
    </td>
    <td>Lukas Podolski</td>

    <td>11</td>
    <td>2</td>
    <td>0</td>
    <td>13</td>
</tr>
<tr>
        <td class="position" rowspan="1"><h3>15.</h3></td>

        <td>akkadian</td>
    <td class="f32">
        <div class="" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="" title="">&nbsp;</div>
    </td>
    <td class="f32">

        <div class="" title="">&nbsp;</div>
    </td>
    <td></td>
    <td>12</td>
    <td>0</td>
    <td>0</td>
    <td>12</td>

</tr>
<tr>
        <td class="position" rowspan="1"><h3>16.</h3></td>
        <td>Maatu</td>
    <td class="f32">
        <div title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div title="">&nbsp;</div>
    </td>
    <td>Fernando Torres</td>
    <td>11</td>
    <td>0</td>

    <td>0</td>
    <td>11</td>
</tr>
<tr>
        <td class="position" rowspan="1"><h3>17.</h3></td>
        <td>pyry</td>
    <td class="f32">
        <div class="flag POR" title="">&nbsp;</div>

    </td>
    <td class="f32">
        <div class="flag se" title="">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="flag GER" title="">&nbsp;</div>
    </td>
    <td>Zlatan Ibrahimovic</td>

    <td>9</td>
    <td>1</td>
    <td>0</td>
    <td>10</td>
</tr>
</tbody>
</table>