<!DOCTYPE html>
<html lang="fi">
<head>
<meta charset="utf-8">
<?php if (isset($meta)) echo $meta; ?>
<title></title>
<link rel="stylesheet" href="<?php echo url('~/css/reset.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/typography.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/ui/south-street/jquery-ui.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/flags16.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/flags32.css'); ?>">
<link rel="stylesheet" href="<?php echo url('~/css/main.css'); ?>">
<?php if (isset($css)) echo $css; ?>
</head>
<body id="default">
<br>
<div id="menu" class="row">
    <div class="column grid_12">
        <ul id="menu">
            <li><a href="http://www.google.com" target="_self" title="Otteluveikkaus" class="current">Otteluveikkaus</a></li>
            <li><a href="http://www.google.com" target="_self" title="Kolmen kärki">Kolmen kärki</a></li>
            <li><a href="http://www.google.com" target="_self" title="Maalikuninkuus">Maalikuninkuus</a></li>
            <li><a href="http://www.google.com" target="_self" title="Tilastot">Tilastot</a></li>
            <li><a href="http://www.google.com" target="_self" title="Kisachat">Kisachat</a></li>
            <li><a href="http://www.google.com" target="_self" title="Säännöt">Säännöt</a></li>
        </ul>
    </div>
</div>

<div id="breadcrumb" class="row">
    <div class="column grid_12">
        <ul id="breadcrumbs" class="xbreadcrumbs">
             <li class="home"><a href="#">Etusivu</a></li>
             <li><div>»</div></li>
             <li><a href="#">Veikkaukset</a></li>
             <li><div>»</div></li>
             <li class="current"><a href="#">Otteluveikkaus</a></li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="column grid_8">
        <?php echo $view; ?>
    </div>
    <div class="column grid_4">
        <h5>Oikea palsta</h5>
        <p>Lorem...</p>
    </div>
</div>
<div class="row">
    <div class="column grid_12">
        Sivun suoritusaika <?php global $starttime; echo (microtime(true) - $starttime) * 1000; ?> millisekuntia.
    </div>
</div>
<script src="<?php echo url('~/js/jquery.js'); ?>"></script>
<script src="<?php echo url('~/js/jquery-ui.js'); ?>"></script>
<?php if (isset($scripts)) echo $scripts; ?>
</body>
</html>