<?php $layout = 'layouts/layout.default.phtml'; ?>
<?php block($css); ?>
<link rel="stylesheet" href="<?php echo url('~/css/tablesorter.css'); ?>">
<?php block(); ?>
<h1><?php echo $title; ?></h1>
<hr>
<table id="points" class="tablesorter">
 <thead>
   <tr>
        <th><img src="<?php echo url('~/img/ranking.png'); ?>" width="16" height="16" title="Sijoitus" alt="Sijoitus"></th>
        <th>Nimi</th>
        <th><img src="<?php echo url('~/img/medal-gold.png'); ?>" width="16" height="16" title="Voittaja" alt="Voittaja"></th>
        <th><img src="<?php echo url('~/img/medal-silver.png'); ?>" width="16" height="16" title="Hopeamitalisti" alt="Hopeamitalisti"></th>
        <th><img src="<?php echo url('~/img/medal-bronze.png'); ?>" width="16" height="16" title="Pronssimitalisti" alt="Pronssimitalisti"></th>
        <th>Maalikuningas</th>
        <th><img src="<?php echo url('~/img/soccer.png'); ?>" width="16" height="16" title="Ottelupisteet" alt="Ottelupisteet"></th>
        <th><img src="<?php echo url('~/img/teams.png'); ?>" width="48" height="16" title="Kolmen kärki &trade; pisteet" alt="Kolmen kärki &trade; pisteet"></th>
        <th><img src="<?php echo url('~/img/scorer.png'); ?>" width="16" height="16" title="Maalikuninkuuspisteet" alt="Maalikuninkuuspisteet"></th>
        <th><img src="<?php echo url('~/img/sum.png'); ?>" width="16" height="16" title="Pisteet yhteensä" alt="Pisteet yhteensä"></th>
    </tr>
</thead>
<tbody>
<?php foreach ($points as $point): ?>
<tr>
    <?php if ($point['rowspan'] === 0): ?>
    <td class="position"><?php echo $point['position']; ?>.</td>
    <?php elseif ($point['rowspan'] > 0 && $point['keyrow']): ?>
    <td class="position" rowspan="<?php echo $point['rowspan']; ?>"><h3><?php echo $point['position']; ?>.</h3></td>
    <?php endif; ?>
    <td>
        <?php if ($point['username'] === username): ?>
        <strong><?php echo $point['username']; ?></strong>
        <?php else: ?>
        <?php echo $point['username']; ?>
        <?php endif; ?>
    </td>
    <td class="f32">
        <div class="<?php echo isset($point['winner_abbr']) ? "flag " . $point['winner_abbr'] : ''; ?>" title="<?php echo isset($point['winner']) ? $point['winner'] : ''; ?>">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="<?php echo isset($point['second_abbr']) ? "flag " . $point['second_abbr'] : ''; ?>" title="<?php echo isset($point['second']) ? $point['second'] : ''; ?>">&nbsp;</div>
    </td>
    <td class="f32">
        <div class="<?php echo isset($point['third_abbr']) ? "flag " . $point['third_abbr'] : ''; ?>" title="<?php echo isset($point['third']) ? $point['third'] : ''; ?>">&nbsp;</div>
    </td>
    <td><?php echo isset($point['scorer']) ? $point['scorer'] : (isset($point['scorer_betted']) ? $point['scorer_betted'] : '&nbsp;') ?></td>
    <td><?php echo $point['game_points'] ?></td>
    <td><?php echo $point['team_points'] ?></td>
    <td><?php echo $point['scorer_points'] ?></td>
    <td><?php echo $point['total_points'] ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>