<?php $layout = 'views/layout.login.phtml'; ?>

<?php block($css); ?>
<?php block(); ?>

<h1 class="ui-corner-top">Kirjaudu sisään World Cup 2010 -hupilyöntiin</h1>
<div>
    <div id="login-wrapper"  style="float: left;">
        <form id="login-form" class="registration">
            <label for="username" class="normal">Käyttäjätunnus:</label><br>
            <input id="username" name="username"  type="text" value=""><br>
            <label for="password" class="normal">Salasana:</label><br>
            <input id="password" name="password" type="password" value="">
            <label for="password" class="normal">Salasana (uudestaan):</label><br>
            <input id="password" name="password" type="password" value="">
            <label for="email" class="normal">Sähköpostiosoite:</label><br>
            <input id="email" name="email"  type="text" value=""><br>
            <br>
            <input type="submit" value="Rekisteröidy"> <a href="<?php echo url('~/') ?>">Takaisin</a>
        </form>
    </div>
    <div id="login-google-wrapper" style="float: right;">
        <form id="login-form-google">
            <input type="image" src="<?php echo url('~/img/google-openid.png'); ?>">
        </form>
    </div>
    <div class="clear"></div>
</div>
<h3 class="ui-corner-bottom">Voit rekisteröityä Google-tunnuksellasi klikkaamalla Googlen logoa.</h3>
<?php block($scripts); ?>
<?php block(); ?>