<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title><?php $this->title() ?> | Layout Title</title>
<?php $this->stylesheets(); ?>
</head>
<body>
<div id="content">
    <?php $this->view(); ?>
</div>
<?php $this->javascripts(); ?>
<div>
Execution time <?php global $starttime; echo microtime(true) - $starttime; ?> secs.
</div>
</body>
</html>